### ISSUE TITLE
The classical `tizonia exiting (OMX_ErrorInsufficientResources)`

### ISSUE THREAD

**Issue by esturniolo** [tizonia/docker-tizonia#19] opened 2020-06-07 16:00 UTC
Hi guys.
I see that this issue is a little repetitive. Sorry for posting it again.

```
$ ./docker-tizonia --spotify-album 'Chocolate Starfish & the Hot Dog Flavored Water'
tizonia 0.22.0. Copyright (C) 2020 Juan A. Rubio and contributors
This software is part of the Tizonia project <https://tizonia.org>

[Spotify] [Connecting] : 'e@mail.com'.
[Spotify] [Album search] 'Chocolate Starfish & the Hot Dog Flavored Water'.
[Spotify] [Album] 'Chocolate Starfish And The Hot Dog Flavored Water'.
[Spotify] [Track] [#01] 'Intro' [Limp Bizkit] (1m:19s).
[Spotify] [Track] [#02] 'Hot Dog' [Limp Bizkit] (3m:50s).
[Spotify] [Track] [#03] 'My Generation' [Limp Bizkit] (3m:41s) <Explicit>.
[Spotify] [Track] [#04] 'Full Nelson' [Limp Bizkit] (4m:07s).
[Spotify] [Track] [#05] 'My Way' [Limp Bizkit] (4m:33s) <Explicit>.
[Spotify] [Track] [#06] 'Rollin' (Air Raid Vehicle)' [Limp Bizkit] (3m:34s) <Explicit>.
[Spotify] [Track] [#07] 'Livin' It Up' [Limp Bizkit] (4m:24s) <Explicit>.
[Spotify] [Track] [#08] 'The One' [Limp Bizkit] (5m:43s).
[Spotify] [Track] [#09] 'Getcha Groove On - Dirt Road Mix' [Limp Bizkit] (4m:19s) <Explicit>.
[Spotify] [Track] [#10] 'Take A Look Around' [Limp Bizkit] (5m:21s).
[Spotify] [Track] [#11] 'It'll Be OK' [Limp Bizkit] (5m:06s).
[Spotify] [Track] [#12] 'Boiler' [Limp Bizkit] (7m:00s).
[Spotify] [Track] [#13] 'Hold On' [Limp Bizkit] (5m:48s).
[Spotify] [Track] [#14] 'Rollin' (Urban Assault Vehicle)' [Limp Bizkit] (6m:23s) <Explicit>.
[Spotify] [Track] [#15] 'Outro' [Limp Bizkit] (9m:50s).
[Spotify] [Tracks in queue] '15'.
[Spotify] [Cache]: '/var/tmp/tizonia-tizonia-spotify-e@mail.com'
[Spotify] [Login] 'r8eaz0tuw621b2z1kbq41a2a5' logged in.
[Spotify] [Streaming] : 'Chocolate Starfish & the Hot Dog Flavored Water'.

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_renderer.pulseaudio.pcm:port:0]
 [OMX_ErrorInsufficientResources]
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```
```
$i nxi -A
Audio: Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio driver: snd_hda_intel 
           Device-2: Intel 8 Series/C220 Series High Definition Audio driver: snd_hda_intel 
           Sound Server: ALSA v: k5.4.0-33-generic
```
Any clue?

And just for the record: I got the exact same issue with the snap package. Identical.

Thanks!

**Comment by matthewarmand** [comment] 2020-06-07 16:21
>I see that this issue is a little repetitive. Sorry for posting it again.

No worries, its a different problem this time which is always a sign of progress.

>And just for the record: I got the exact same issue with the snap package. Identical.

If this is the case, its doubtful this is an issue with the Docker container, and is likely to be either a local setup issue, or transferred to the [main repo](https://github.com/tizonia/tizonia-openmax-il), but let's see if we can get a bit more information and context before we do that.

>`OMX_ErrorInsufficientResources`

You'll discover this soon enough if you haven't already, but this is an unfortunately common and generic error within Tizonia. I haven't delved that deeply into the main package source code to figure out why/how to improve it, but this is a generic fallback error you'll see pop up in any number of cases (which is why its so "classical") and isn't necessarily specifically reflective of what's gone wrong.

Enabling debug logs might shed a bit more light onto things. Luckily for the Spotify proxy (and most other proxy code) this is configurable with an environment variable, so its easy enough to do this in the Docker container by adding the following line to `Dockerfile` and re-building the image locally using `build.sh`:

```
ENV TIZONIA_SPOTIFYPROXY_DEBUG=1
```

**Comment by esturniolo** [comment] 2020-06-07 16:53
Thanks for your fast response.

> ENV TIZONIA_SPOTIFYPROXY_DEBUG=1

You can see the logs in the attach.

I forgot to mention that happens the same with Youtube and TuneIn. So I guess that all the services has this issues.

[logs.log](https://github.com/tizonia/docker-tizonia/files/4742509/logs.log)

**Comment by juanrubio** [comment] 2020-06-07 19:54
Hi @esturniolo / @matthewarmand 

> tizonia exiting (OMX_ErrorInsufficientResources).
> [OMX.Aratelia.audio_renderer.pulseaudio.pcm:port:0]

it looks like Tizonia is unable to connect to the PulseAudio server. This typically occurs when Tizonia has not got the necessary access rights to talk to the PA server.  That could happen for a number of reasons, so the root cause is not always the same.

>  got the exact same issue with the snap package. Identical.

The Snap package has been plagued in the past with this type of issue. I've pushed just a couple of days ago a fresh version of the Snap package which brings it to v0.22.0. It works well for me on Ubuntu Focal with Gnome Shell. If you are interested, feel free to open an issue in the snap repo and I'll look at the snap issue there:
- https://github.com/tizonia/tizonia-snap

Back to the `OMX_ErrorInsufficientResources` problem in the docker container:

I believe this could again be some sort of permissions problem. 

In `docker-tizonia`, the Tizonia instance that runs in the container needs to talk to the PulseAudio daemon that runs in the host (Snap packages with strict confinement basically need to accomplish this same thing, hence the similar problems). 

There are two things that need to be made available to the client (Tizonia) running in the container, one is the 'location' of the PulseAudio daemon socket and the other is the PulseAudio authentication cookie from the host:

- The default location of the PulseAudio socket (I'm assuming Ubuntu here) is:
```
➜  ~  file /run/user/$(id -u)/pulse/native
/run/user/1000/pulse/native: socket
➜  ~  ls -l /run/user/$(id -u)/pulse/native
srwxrwxrwx 1 juan juan 0 Jun  3 09:52 /run/user/1000/pulse/native
```

- The location of the PulseAudio cookie is:
```
➜  ~  ls -l $HOME/.config/pulse/cookie 
-rw------- 1 juan juan 256 Apr  8  2014 /home/juan/.config/pulse/cookie
➜  ~  file $HOME/.config/pulse/cookie         
/home/juan/.config/pulse/cookie: zlib compressed data
```

The `run.sh` script in docker image uses the following trick to make sure that Tizonia can access the host's cookie and the socket from the container. 
https://github.com/tizonia/docker-tizonia/blob/9eb99416fe868c4cfc06e385dea6e8c23d133c97/run.sh#L7

This trick is not completely 'generic'. as it assumes that the PulseAudio server in the host and the Tizonia instance in the container run under the same user (same UID and GID). Also, the path `$HOME/.config/pulse/cookie` needs to be accessible from the container. 

I'm not sure which of these elements is not working in @esturniolo 's case, so I mention in case it rings any bells.

Some good info about this in the Arch wiki:
https://wiki.archlinux.org/index.php/PulseAudio/Configuration#Connection_&_authentication

**Comment by esturniolo** [comment] 2020-06-08 12:58
I see. But there is something strange here.
I changed from Kubuntu (20.04) to Ubuntu (20.04) this week and in the same machine, with the same hardware I used docker-tizonia with no issues. But now I can't. So there is something with the audio server that Ubuntu manage a little bit different.

May be with this info you can get some clue.

Thanks for the detail explanation.

**Comment by matthewarmand** [comment] 2020-06-08 16:25
@esturniolo that's interesting, I'd think the PulseAudio configuration for both should be similar enough to be interoperable. Are you having audio issues with other applications through Pulse, or does this seem limited to `tizonia` currently?

**Comment by esturniolo** [comment] 2020-06-08 16:57
Hi @matthewarmand.
The funny thing is that I just reboot my laptop (was up since Friday) and now all works correctly.
With ANY changes made.

So I think that the Pulse server needs a restart to be able to use tizonia. I don't know if someone comment this before. I didn't read this in the docs (may beI just skipped without realizing it), but may be a simple reboot it's a must after installation.

**Comment by matthewarmand** [comment] 2020-06-08 18:01
Ah, that's very interesting. I don't remember whether that's necessary normally with `tizonia`, I don't think it is but its a good workaround to keep in mind for the `[OMX.Aratelia.audio_renderer.pulseaudio.pcm:port:0]` case.

In case someone else stumbles upon this, it's probably not necessary to restart the machine, its possible that just [restarting the PulseAudio daemon](https://askubuntu.com/questions/15223/how-can-i-restart-pulseaudio-without-having-to-logout) could be sufficient.

Is everything working as expected now @esturniolo?

**Comment by juanrubio** [comment] 2020-06-08 18:55
The PulseAudio server usually re-writes the cookie when it starts. Also, both the pulse audio cookie and the server socket string are (optionally) stored in the properties of the X11 root window. E.g.:
```
$ xprop -root                          
_NET_WM_ICON_NAME(UTF8_STRING) = 
PULSE_COOKIE(STRING) = "785eaacbc95d8ae32ee3298c6ecb207bb246b9be9b2c84f1d17ae6571fb0224b973164fb2eddb5556f226ea3fe768611d84bd98883a01f9c5cba74458434e4cb5086f4e260c86e754385ae41f4d9afe6641ac75f86dc75d38a829723dbe2142f5ea3e81ce862736ecf4604feb44e1c29f87967e63d8fd9fd06a0056dfa2d7d3b229690ccffc4a0cd0d54af9fd5d7866aa9e495c41948e3957347d55ac1f77cf4643f3b2a1920ea23cced3c390997ba8dbb04a5c21c9938a23d6f8b4f6649ce51cc5bf644b0e91ab57cade86d3e6cf9b557e8318384d24fa32ec4b417793a7bff7deaffb4e60ee10131d444898e2a1e402295e4bb59f5b83061c50143bd247bd1"
PULSE_SERVER(STRING) = "{4bbc8c2b9e4e4f2da9b57d6d6d7590af}unix:/run/user/1000/pulse/native"
```

libpulseaudio (which Tizonia uses to access PulseAudio) has some elaborate mechanism to find these two elements from one of these locations: the X11 root window, environment variables (PULSE_COOKIE, PULSE_SERVER) or the default locations in the file system. 

So I don't necessarily think that restarting PulseAudio is a pre-requisite to run Tizonia inside the container, but it is definitely a good tip when things stop working. Perhaps restarting the desktop session might also help.

**Comment by esturniolo** [comment] 2020-06-08 19:31
> Is everything working as expected now @esturniolo?

Yes, it's all working now @matthewarmand.

@matthewarmand @juanrubio 
I think that restart at least the Pulseaudio server would be nice. I think that whoever uses tizonia would not care if the Pulseaudio Server is restarted or not.

**Comment by matthewarmand** [comment] 2020-06-08 20:38
Perfect, I'll close this issue for now then.

@juanrubio if there's enough content for something like this, that pulse restart tip would fit well in some kind of "Troubleshooting" section in the docs. Maybe something to think about for the future if you think something like that would be useful

**Closed as completed by matthewarmand** 2020-06-08 20:38 UTC

**Comment by juanrubio** [comment] 2020-06-12 21:25
@matthewarmand / @esturniolo 

I've added a page about the docker image in the official docs, which includes a 'Known issues' section:

- https://docs.tizonia.org/manual/docker.html

This was long overdue, so thanks to both for the suggestions!
